# Description: This file is used to build the devcontainer at runtime.
# Add additional dependencies below the `FROM` line as needed.

FROM ghcr.io/containercraft/devcontainer:latest

# Install additional dependencies by extending the base image
#ARG DEBIAN_FRONTEND=noninteractive
#ARG APT_PACKAGES="\
#"
#
#RUN set -ex \
#    && apt-get update \
#    && apt-get install -y $APT_PACKAGES \
#    && apt-get clean \
#    && rm -rf /var/lib/apt/lists/* \
#    && echo
