config:
  # AWS Module Configuration
  aws:
    enabled: false
    profile: smdc-cba
    region: us-east-1
    eks:
      enabled: false
      clusters:
        - name: dev-controlplane-blue
          version: "1.29"
          node_groups:
            - name: default
              instance_types:
                - t3.medium
              scaling_config:
                desired_size: 2
                max_size: 4
                min_size: 1
    access_key_id: AKIAZV4C4BY73DTWKLBC
    secret_access_key:
      secure: AAABAMB+REOMPMPbzL2/ZiGM2eBqviSf83JGwOkuzkSLXBrRrZdQzu8ESVYN4Y8feJF7yMNLAjf6wW/UJkI9TvGs1WeOLUZJ

  # Compliance Configuration aligned with revision08 (and now revision09)
  compliance:
    project:
      environment: "prod-us-east"
      production: true
      ownership:
        owner:
          name: "default-owner"
          contacts: []
        operations:
          name: "default-ops"
          contacts: []
      ato:
        id: "1234-ATO"
        authorized: "2025-03-27T00:00:00Z"
        eol: "2028-03-27T00:00:00Z"
    fisma:
      level: moderate
      mode: warn
    nist:
      auxiliary: []
      exceptions: []

  # Kubernetes Module Configuration
  kubernetes:
    enabled: false
    prometheus:
      enabled: false
      namespace: monitoring
      version: "45.7.1"
      openunison_enabled: false
    crossplane:
      enabled: false
      namespace: crossplane-system
      version: "1.18.0"
      providers:
        - provider-aws
        - provider-kubernetes
      aws_provider_version: "v0.43.1"
      kubernetes_provider_version: "v0.10.0"
      enable_external_secret_stores: true
      enable_composition_revisions: true
    flux:
      enabled: false
      namespace: flux-system
      version: "2.x"
      operator_version: "0.10.0"
      storage_class: "gp2"
      storage_size: "10Gi"
      network_policy: true
      multitenant: false
      cluster_domain: "cluster.local"
      reconcile_interval: "1h"
      reconcile_timeout: "3m"
      concurrent_reconciles: 10
      requeue_dependency_interval: "5s"
      components:
        - source-controller
        - kustomize-controller
        - helm-controller
        - notification-controller
        - image-reflector-controller
        - image-automation-controller
    cert_manager:
      enabled: false

