config:

  # Top-level Compliance Configuration (used as a source merged into AWSConfig)
  compliance:
    project:
      environment: "preprod-na-blue"
      production: false
      ownership:
        owner:
          name: "developer"
          contacts: []
        operations:
          name: "deving-ops"
          contacts: []
      ato:
        id: "1234-ATO"
        authorized: "2024-03-27T00:00:00Z"
        eol: "2028-03-27T00:00:00Z"
    fisma:
      level: "moderate"
      mode: "warn"
    nist:
      auxiliary: []
      exceptions: []

  # AWS Module Configuration
  aws:
    # BaseConfigModel fields
    enabled: false
    metadata:
      tags:
        team: "platform"
        application: "ucp"
      labels:
        env: "preprod"
      annotations: {}

    # AWS-specific configuration
    profile: "smdc-cba"
    region: "us-east-1"
    bucket: "ucp-devops"

    network:
      vpc_cidr: "10.0.0.0/16"
      subnet_cidrs:
        public:
          - "10.0.1.0/24"
          - "10.0.2.0/24"
        private:
          - "10.0.3.0/24"
          - "10.0.4.0/24"
      availability_zones:
        - "us-east-1a"
        - "us-east-1b"
      enable_nat_gateway: true
      enable_vpn_gateway: false
      enable_flow_logs: true
      metadata:
        tags: {}
        labels: {}
        annotations: {}

    security:
      enable_security_hub: true
      enable_guard_duty: true
      enable_config: true
      enable_cloudtrail: true
      kms_deletion_window: 30
      enable_key_rotation: true
      metadata:
        tags: {}
        labels: {}
        annotations: {}

    # AWS EKS specific configuration
    eks:
      enabled: false
      clusters:
        - name: "preprod-controlplane-blue"
          enabled: false
          version: "1.29"
          endpoint_private_access: true
          endpoint_public_access: true
          node_groups:
            - name: "default"
              instance_types:
                - "t3.medium"
              scaling_config:
                desired_size: 2
                max_size: 4
                min_size: 1
              subnet_ids: null
              metadata:
                tags: {}
                labels: {}
                annotations: {}
          metadata:
            tags: {}
            labels: {}
            annotations: {}

    # AWS Credentials
    access_key_id: "AKIAZV4C4BY73DTWKLBC"
    secret_access_key:
      secure: "AAABAMB+REOMPMPbzL2/ZiGM2eBqviSf83JGwOkuzkSLXBrRrZdQzu8ESVYN4Y8feJF7yMNLAjf6wW/UJkI9TvGs1WeOLUZJ"

  # Kubernetes Module Configuration remains unchanged or can be expanded similarly
  kubernetes:
    enabled: false
    prometheus:
      enabled: false
      namespace: "monitoring"
      version: "45.7.1"
      openunison_enabled: false
    crossplane:
      enabled: false
      namespace: "crossplane-system"
      version: "1.18.0"
      providers:
        - "provider-aws"
        - "provider-kubernetes"
      aws_provider_version: "v0.43.1"
      kubernetes_provider_version: "v0.10.0"
      enable_external_secret_stores: true
      enable_composition_revisions: true
    flux:
      enabled: false
      namespace: "flux-system"
      version: "2.x"
      operator_version: "0.10.0"
      storage_class: "gp2"
      storage_size: "10Gi"
      network_policy: true
      multitenant: false
      cluster_domain: "cluster.local"
      reconcile_interval: "1h"
      reconcile_timeout: "3m"
      concurrent_reconciles: 10
      requeue_dependency_interval: "5s"
      components:
        - "source-controller"
        - "kustomize-controller"
        - "helm-controller"
        - "notification-controller"
        - "image-reflector-controller"
        - "image-automation-controller"
    cert_manager:
      enabled: false

